- DOCUMENT.md
- unittest/junit_report_xml_test.go
- unittest/nunit_report_xml.go
- unittest/nunit_report_xml_test.go
- unittest/test_job_test.go
- unittest/test_runner_test.go
- unittest/test_suite_test.go
- unittest/utils.go
- unittest/utils_test.go
- unittest/validators/common_test.go
- unittest/valueutils/valueutils.go
- unittest/xunit_report_xml.go
- unittest/xunit_report_xml_test.go
Update documentation with missing assertions, remove duplication code for formatter testing.
> Quality improvements

- install-binary.sh
> Corrected status option on sha256sum.

- install-binary.sh
- unittest/validators/contains_validator.go
- unittest/validators/contains_validator_test.go
- unittest/validators/equal_raw_validator.go
- unittest/validators/equal_raw_validator_test.go
- unittest/validators/equal_validator.go
- unittest/validators/equal_validator_test.go
- unittest/validators/failed_template_validator.go
- unittest/validators/failed_template_validator_test.go
- unittest/validators/is_apiversion_validator.go
- unittest/validators/is_apiversion_validator_test.go
- unittest/validators/is_empty_validator.go
- unittest/validators/is_empty_validator_test.go
- unittest/validators/is_kind_validator.go
- unittest/validators/is_kind_validator_test.go
- unittest/validators/is_null_validator.go
- unittest/validators/is_null_validator_test.go
- unittest/validators/is_subset_validator.go
- unittest/validators/is_subset_validator_test.go
- unittest/validators/match_regex_raw_validator.go
- unittest/validators/match_regex_raw_validator_test.go
- unittest/validators/match_regex_validator.go
- unittest/validators/match_regex_validator_test.go
- unittest/validators/snapshot_raw_validator.go
- unittest/validators/snapshot_raw_validator_test.go
- unittest/validators/snapshot_validator.go
- unittest/validators/snapshot_validator_test.go
Cleanup download output
Simplify validations and cleanup caused duplicated tests.
> Cleanup download output

- docker-build.sh
> Remove spaces in asignment.

- docker-build.sh
Override entrypoint to search for helm version, not plugin help information.
> Override entrypoint to search for helm version

- docker-build.sh
> Limit plugin download to 1.

- DOCKER_README.md
- Dockerfile
- docker-build.sh
Update Dockerfile to be aware of helm2 and helm3. 
Add readme for dockerhub.
> Update Dockerfile to be aware of helm2 and helm3

- unittest/assertion.go
Fix filenotfound assertion validation, also return full path instead of single file. (resolves #39, #53)
> Fix filenotfound assertion validation

- .circleci/config.yml
- Makefile
- docker-build.sh
Update docker deployment and versioning order, newest version will be deployed as last.
> Update docker deployment and versioning order

- pkg/unittest/.snapshots/TestV2RunnerOkWithFailedTests
- pkg/unittest/.snapshots/TestV2RunnerOkWithPassedTests
- pkg/unittest/.snapshots/TestV3RunnerOkWithFailedTests
- pkg/unittest/.snapshots/TestV3RunnerOkWithPassedTests
- pkg/unittest/validators/common.go
- pkg/unittest/validators/failed_template_validator.go
- pkg/unittest/validators/match_regex_raw_validator.go
- pkg/unittest/validators/match_regex_raw_validator_test.go
- pkg/unittest/validators/match_regex_validator.go
- pkg/unittest/validators/match_regex_validator_test.go
- test/data/v2/basic/templates/configmap.yaml
- test/data/v2/basic/tests/configmap_test.yaml
- test/data/v2/basic/tests_failed/configmap_test.yaml
- test/data/v3/basic/templates/configmap.yaml
- test/data/v3/basic/tests/configmap_test.yaml
- test/data/v3/basic/tests_failed/configmap_test.yaml
Added required field validation for regex pattern. 
Added new tests verifying regex with multilines.
> MultilineRegexValidation

- pkg/unittest/.snapshots/TestV2RunJobWithChartSettings
- pkg/unittest/.snapshots/TestV3RunJobWithChartSettings
- pkg/unittest/test_job.go
- pkg/unittest/test_job_test.go
- pkg/unittest/test_suite.go
- test/data/v2/basic/tests/deployment_test.yaml
- test/data/v3/basic/tests/deployment_test.yaml
Add feature to override chart version in TestSuite and TestJob,
Including validation tests.
> ChartVersionOverride

- AlpineTest.Dockerfile
- CentOSTest.Dockerfile
- install-binary.sh
* Fix typo on curl download (resolves #77)
* Fix sha256sum on CentOs, while keeping sha256sum validation working on alpine (resolves #78)
> InstallBinaryScript

- install-binary.sh
Check if OS is linux before checking distro (resolves #82)
> Only search for os-release when OS is linux.

- README.md
Hello,
Some people look for an alternative to helm-unittest, but it is quite difficult. So I add them to README.md. Hope this will be helpful to others.
Best regards,
Kamil Breguła
> Adds alternatives for this project to README.md

- pkg/unittest/assertion.go
- pkg/unittest/test_job.go
- pkg/unittest/test_runner.go
- pkg/unittest/test_runner_test.go
- pkg/unittest/test_suite.go
- test/data/v2/basic/tests/deployment_test.yaml
- test/data/v3/basic/tests/deployment_test.yaml
- Add top level values files (resolve #91)
- Fix minor code analysis recommendations
> Add values to suitelevel and updated tests.

- CHANGELOG.md
- FAQ.md
- README.md
Added FAQ.md with first question.
> Add initial FAQ and update related documentation to point to the FAQ.

- pkg/unittest/.snapshots/TestV2RunnerOkWithAbsoluteOverrideValuesPassedTests
- pkg/unittest/.snapshots/TestV2RunnerOkWithOverrideValuesPassedTests
- pkg/unittest/.snapshots/TestV2RunnerOkWithPassedTests
- pkg/unittest/.snapshots/TestV3RunnerOkWithAbsoluteOverrideValuesPassedTests
- pkg/unittest/.snapshots/TestV3RunnerOkWithOverrideValuesPassedTests
- pkg/unittest/.snapshots/TestV3RunnerOkWithPassedTests
- test/data/v2/basic/tests/ingress_test.yaml
- test/data/v3/basic/tests/ingress_test.yaml
Adding examples to validate nullable maps (resolve #107)
> Add test examples with mappings.

- Makefile
- install-binary.sh
> Added macos-arm64 to build targets.

- pkg/unittest/test_runner.go
- pkg/unittest/test_suite.go
- pkg/unittest/test_suite_test.go
- plugin.yaml
Fixes https://github.com/quintush/helm-unittest/issues/111
> Fixed issue causing unwanted side-effects between job executions

- CHANGELOG.md
- DOCUMENT.md
- sonar-project.properties
Bump version
Update changelog with fixed and new features 
Update documentation with new assertion.
> Bump version

- pkg/unittest/validators/contains_document_validator.go
Remove left over debug statement.
> fix: remove debug statement in `containsDocument` assertion

- pkg/unittest/validators/common.go
- pkg/unittest/validators/contains_validator.go
- pkg/unittest/validators/is_subset_validator.go
- pkg/unittest/validators/is_subset_validator_test.go
> isSubset can assert for multiple elements
